var userInfo = function() {
  return { 
  	"id": 113,
  	"accountName": "18602029524",
  	"pwd": null,
  	"realName": null,
  	"photo": null,
  	"referralId": null,
  	"referralName": null,
  	"companyName": null,
  	"province": null,
  	"provinceId": null,
  	"city": null,
  	"cityId": null,
  	"area": null,
  	"areaId": null,
  	"address": null,
  	"mobilePhone": "18602029524",
  	"email": null,
  	"qq": null,
  	"registerTime": "2016-12-08 10:51:27",
  	"integral": 0,
  	"gold": 0,
  	"level": 1,
  	"status": 1,
  	"wxNickName": null,
  	"wxOpenId": null,
  	"wxHeadPhoto": null,
  	"wxUnionId": null,
  	"sex": null,
  	"birthday": null,
  	"memberType": 4,
  	"wxQrcodeTicket": null,
  	"totalIntegral": 0,
  	"integralLevel": 1,
  	"byAgentUserId": null,
  	"byAgent": null,
  	"wallet": 0,
  	"confirmPwd": null,
  	"validCode": null,
  	"referralPhone": null,
  	"birthdayStr": null,
  	"appId": null,
  	"stillCount": null,
  	"channel": null,
  	"hadWithdrawlasAmout": null
  	"expires": 31536000,
  	"time": 1481179362298
	}

}
